import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

const REQUIRED_THEME_TOKENS = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'destructive-foreground',
  'border',
  'input',
  'ring',
  'radius',
] as const;

const SCRIPT_ROOT = path.resolve(process.cwd(), 'scripts');
const TEMP_WORKSPACES: string[] = [];

type ThemeSeed = {
  id: string;
  cssPath: string;
  contractPath: string;
  tokenCoverage?: string[];
};

const createTempWorkspace = () => {
  const dirPath = fs.mkdtempSync(path.join(os.tmpdir(), 'mezmer-theme-test-'));
  TEMP_WORKSPACES.push(dirPath);
  return dirPath;
};

const writeJson = (
  workspacePath: string,
  relativePath: string,
  data: unknown,
) => {
  const absolutePath = path.join(workspacePath, relativePath);
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(
    `${absolutePath}`,
    `${JSON.stringify(data, null, 2)}\n`,
    'utf8',
  );
};

const writeText = (
  workspacePath: string,
  relativePath: string,
  content: string,
) => {
  const absolutePath = path.join(workspacePath, relativePath);
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, content, 'utf8');
};

const readJson = <T>(workspacePath: string, relativePath: string): T => {
  const absolutePath = path.join(workspacePath, relativePath);
  return JSON.parse(fs.readFileSync(absolutePath, 'utf8')) as T;
};

const readText = (workspacePath: string, relativePath: string) => {
  const absolutePath = path.join(workspacePath, relativePath);
  return fs.readFileSync(absolutePath, 'utf8');
};

const seedWorkspace = (
  workspacePath: string,
  options?: {
    themes?: ThemeSeed[];
    activeThemeId?: string;
  },
) => {
  const themes = options?.themes ?? [
    {
      id: 'default',
      cssPath: 'src/themes/default.css',
      contractPath: 'ai/contracts/themes/default-theme.contract.json',
    },
    {
      id: 'slate',
      cssPath: 'src/themes/slate.css',
      contractPath: 'ai/contracts/themes/slate-theme.contract.json',
    },
  ];

  writeJson(workspacePath, 'ai/contracts/index.json', {
    version: '1.0.0',
    components: [],
    themes: themes.map((theme) => ({
      id: theme.id,
      contractPath: theme.contractPath,
      cssPath: theme.cssPath,
    })),
  });

  themes.forEach((theme) => {
    writeText(
      workspacePath,
      theme.cssPath,
      `:root { --mz-primary: 0 0% 0%; }\n`,
    );

    writeJson(workspacePath, theme.contractPath, {
      id: theme.id,
      displayName: theme.id,
      version: '1.0.0',
      cssPath: theme.cssPath,
      modes: ['light', 'dark'],
      tokenPrefix: '--mz-',
      tokenCoverage: theme.tokenCoverage ?? [...REQUIRED_THEME_TOKENS],
    });
  });

  writeJson(workspacePath, 'ai/theme.active.json', {
    themeId: options?.activeThemeId ?? themes[0]?.id ?? 'default',
    mode: 'system',
    updatedAt: '2026-04-16T00:00:00.000Z',
  });

  writeText(
    workspacePath,
    'src/themes/active.css',
    '/* Auto-generated by pnpm theme:apply. */\n@import "./default.css";\n',
  );
};

const runScript = (
  workspacePath: string,
  scriptName: string,
  args: string[] = [],
) => {
  const scriptPath = path.join(SCRIPT_ROOT, scriptName);

  return spawnSync('node', [scriptPath, ...args], {
    cwd: workspacePath,
    encoding: 'utf8',
  });
};

afterEach(() => {
  TEMP_WORKSPACES.forEach((workspacePath) => {
    fs.rmSync(workspacePath, { recursive: true, force: true });
  });
  TEMP_WORKSPACES.length = 0;
});

describe('Theme scripts', () => {
  it('theme:list returns active theme and theme registry', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath, { activeThemeId: 'default' });

    const result = runScript(workspacePath, 'theme-list.mjs');
    expect(result.status).toBe(0);

    const output = JSON.parse(result.stdout) as {
      activeThemeId: string | null;
      themes: Array<{ id: string }>;
    };

    expect(output.activeThemeId).toBe('default');
    expect(output.themes.map((theme) => theme.id)).toEqual([
      'default',
      'slate',
    ]);
  });

  it('theme:apply updates active theme state and active css import', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath);

    const result = runScript(workspacePath, 'theme-apply.mjs', [
      '--theme',
      'slate',
      '--mode',
      'dark',
    ]);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain("Applied theme 'slate' with mode 'dark'.");

    const activeTheme = readJson<{
      themeId: string;
      mode: string;
      updatedAt: string;
    }>(workspacePath, 'ai/theme.active.json');

    expect(activeTheme.themeId).toBe('slate');
    expect(activeTheme.mode).toBe('dark');
    expect(activeTheme.updatedAt).toBeTruthy();

    const activeCss = readText(workspacePath, 'src/themes/active.css');
    expect(activeCss).toContain('@import "./slate.css";');
  });

  it('theme:apply fails when --theme is missing', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath);

    const result = runScript(workspacePath, 'theme-apply.mjs');

    expect(result.status).toBe(1);
    expect(result.stderr).toContain(
      'Missing required argument: --theme <theme-id>',
    );
  });

  it('theme:apply fails when mode is invalid', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath);

    const result = runScript(workspacePath, 'theme-apply.mjs', [
      '--theme',
      'default',
      '--mode',
      'neon',
    ]);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain(
      'Invalid mode. Allowed values: light, dark, system',
    );
  });

  it('theme:apply fails for unknown theme id', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath);

    const result = runScript(workspacePath, 'theme-apply.mjs', [
      '--theme',
      'unknown-theme',
    ]);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('Unknown theme id: unknown-theme');
  });

  it('theme:apply fails when selected theme css file is missing', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath);

    fs.rmSync(path.join(workspacePath, 'src/themes/slate.css'));

    const result = runScript(workspacePath, 'theme-apply.mjs', [
      '--theme',
      'slate',
    ]);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain(
      'Theme CSS file is missing: src/themes/slate.css',
    );
  });

  it('theme:create scaffolds theme files and updates theme registry', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath);

    const result = runScript(workspacePath, 'theme-create.mjs', [
      '--id',
      'brand-x',
      '--from',
      'default',
    ]);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain("Created theme 'brand-x' from 'default'.");

    const createdCssPath = path.join(workspacePath, 'src/themes/brand-x.css');
    const createdContractPath = path.join(
      workspacePath,
      'ai/contracts/themes/brand-x-theme.contract.json',
    );

    expect(fs.existsSync(createdCssPath)).toBe(true);
    expect(fs.existsSync(createdContractPath)).toBe(true);

    const createdContract = readJson<{
      id: string;
      extendsTheme?: string;
      cssPath: string;
    }>(workspacePath, 'ai/contracts/themes/brand-x-theme.contract.json');

    expect(createdContract.id).toBe('brand-x');
    expect(createdContract.extendsTheme).toBe('default');
    expect(createdContract.cssPath).toBe('src/themes/brand-x.css');

    const indexJson = readJson<{
      themes: Array<{ id: string }>;
    }>(workspacePath, 'ai/contracts/index.json');

    expect(indexJson.themes.some((theme) => theme.id === 'brand-x')).toBe(true);
  });

  it('theme:create fails when --id is missing', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath);

    const result = runScript(workspacePath, 'theme-create.mjs');

    expect(result.status).toBe(1);
    expect(result.stderr).toContain(
      'Missing required argument: --id <theme-id>',
    );
  });

  it('theme:create fails for invalid theme id', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath);

    const result = runScript(workspacePath, 'theme-create.mjs', [
      '--id',
      'Brand_X',
    ]);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('Theme id must match ^[a-z0-9-]+$');
  });

  it('theme:create fails for duplicate theme id', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath);

    const result = runScript(workspacePath, 'theme-create.mjs', [
      '--id',
      'default',
    ]);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('Theme id already exists: default');
  });

  it('theme:create fails when base theme is missing', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath);

    const result = runScript(workspacePath, 'theme-create.mjs', [
      '--id',
      'brand-y',
      '--from',
      'missing-base',
    ]);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('Base theme not found: missing-base');
  });

  it('validate:contracts passes for valid fixture', () => {
    const workspacePath = createTempWorkspace();
    seedWorkspace(workspacePath);

    const result = runScript(workspacePath, 'validate-contracts.mjs');

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('Contract validation passed.');
  });

  it('validate:contracts fails when token coverage misses ring', () => {
    const workspacePath = createTempWorkspace();

    const tokenCoverageWithoutRing = REQUIRED_THEME_TOKENS.filter(
      (token) => token !== 'ring',
    );

    seedWorkspace(workspacePath, {
      themes: [
        {
          id: 'default',
          cssPath: 'src/themes/default.css',
          contractPath: 'ai/contracts/themes/default-theme.contract.json',
          tokenCoverage: tokenCoverageWithoutRing,
        },
      ],
      activeThemeId: 'default',
    });

    const result = runScript(workspacePath, 'validate-contracts.mjs');

    expect(result.status).toBe(1);
    expect(result.stderr).toContain(
      'tokenCoverage is missing required token: ring.',
    );
  });
});
